//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhScraper.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public Vacancy()
        {
            this.VacancyPageUrl = "";
            this.VacancyPageHtml = "";
            this.ScrampingDateTime = "";
            this.VacancyPublicationDate = "";
            this.DesiredPosition = "";
            this.Salary = "";
            this.VacancyPhotoUrl = "";
            this.FIO = "";
            this.AboutMe = "";
            this.WorkExperience = "";
            this.Age = "";
            this.Phone = "";
            this.Gender = "";
            this.Address = "";
            this.FieldOfActivity = "";
            this.MailDeliveryStatus = 0;
            this.ReadyToBusinessTrip = "";
            this.EMail = "";
            this.WorkHistory = "";
            this.RelativeFilePath = "";
            this.HhVacancyID = "";
        }
    
        public int VacancyID { get; set; }
        public string VacancyPageUrl { get; set; }
        public string VacancyPageHtml { get; set; }
        public string ScrampingDateTime { get; set; }
        public string VacancyPublicationDate { get; set; }
        public string DesiredPosition { get; set; }
        public string Salary { get; set; }
        public string VacancyPhotoUrl { get; set; }
        public string FIO { get; set; }
        public string AboutMe { get; set; }
        public string WorkExperience { get; set; }
        public string Age { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string FieldOfActivity { get; set; }
        public Nullable<int> MailDeliveryStatus { get; set; }
        public string ReadyToBusinessTrip { get; set; }
        public string EMail { get; set; }
        public string WorkHistory { get; set; }
        public string RelativeFilePath { get; set; }
        public string HhVacancyID { get; set; }
    }
}
