//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Notificator.Core.Model
{
    public partial class Event
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<UserEventLink> UserEventLinks
        {
            get
            {
                if (_userEventLinks == null)
                {
                    var newCollection = new FixupCollection<UserEventLink>();
                    newCollection.CollectionChanged += FixupUserEventLinks;
                    _userEventLinks = newCollection;
                }
                return _userEventLinks;
            }
            set
            {
                if (!ReferenceEquals(_userEventLinks, value))
                {
                    var previousValue = _userEventLinks as FixupCollection<UserEventLink>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserEventLinks;
                    }
                    _userEventLinks = value;
                    var newValue = value as FixupCollection<UserEventLink>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserEventLinks;
                    }
                }
            }
        }
        private ICollection<UserEventLink> _userEventLinks;

        #endregion
        #region Association Fixup
    
        private void FixupUserEventLinks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserEventLink item in e.NewItems)
                {
                    item.Event = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserEventLink item in e.OldItems)
                {
                    if (ReferenceEquals(item.Event, this))
                    {
                        item.Event = null;
                    }
                }
            }
        }

        #endregion
    }
}
