//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Notificator.Core.Model
{
    public partial class EventInfo
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public string Name
        {
            get;
            set;
        }
    
        public Nullable<int> UserCount
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> JoinDate
        {
            get;
            set;
        }

        #endregion
    }
}
