//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Notificator.Core.Model
{
    public partial class NotificationLogItem
    {
        #region Primitive Properties
    
        public int UserId
        {
            get;
            set;
        }
    
        public string UserName
        {
            get;
            set;
        }
    
        public int LinkId
        {
            get;
            set;
        }
    
        public System.DateTime JoinDate
        {
            get;
            set;
        }
    
        public string EventName
        {
            get;
            set;
        }
    
        public int EventId
        {
            get;
            set;
        }

        #endregion
    }
}
