//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18052
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureRobot.FuroWare.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"ko-kr,Microsoft,en-us,Microsoft,de-de,Microsoft,es-es,Microsoft,fr-fr,Microsoft,it-it,Microsoft,ja-jp,Microsoft,zh-cn,Microsoft,Heather22k_HQ,Acapela,Kenny22k_HQ,Acapela,Laura22k_HQ,Acapela,Micah22k_HQ,Acapela,Nelly22k_HQ,Acapela,Ryan22k_HQ,Acapela,Saul22k_HQ,Acapela,Tracy22k_HQ,Acapela,Will22k_HQ,Acapela")]
        public string VoiceDB {
            get {
                return ((string)(this["VoiceDB"]));
            }
        }
    }
}
