// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace CinemaSchedule.DataBase.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class First : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First));

        string IMigrationMetadata.Id
        {
            get { return "201611221737158_First"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
